-- Could not auto-generate a down migration.
-- Please write an appropriate down migration for the SQL below:
-- CREATE TYPE recommend_return_type AS (
--   product_id INT,
--   recommendation_score NUMERIC
-- );
