-- Could not auto-generate a down migration.
-- Please write an appropriate down migration for the SQL below:
-- CREATE TEMP TABLE recommend_return_type (
--   product_id INT,
--   recommendation_score NUMERIC
-- );
