-- Could not auto-generate a down migration.
-- Please write an appropriate down migration for the SQL below:
-- CREATE TYPE recommended_product AS (
--     product_id INT,
--     recommendation_score NUMERIC
-- );
